name: 'citibike_dbt'
version: '1.0'
config-version: 2

profile: 'citibike_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]   # <-- 👈 You need this line

models:
  citibike_dbt:
    marts:
      dim:
        +materialized: table
      fact:
        +materialized: table
    staging:
      +materialized: view
