name: dsai_project

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11.0
  - pandas=2.3.0
  - sqlalchemy=2.0.41
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - dagster=1.10.19
  - dagster-webserver=1.10.19
  - ipykernel=6.29.5
  - pip=25.1.1
  - pip:
      - duckdb==1.3.0
      - duckdb-engine==0.17.0
      - meltano==3.6.0
      - dbt-core==1.9.8
      - dbt-bigquery==1.9.2