name: dsai_project
channels:
  - defaults
dependencies:
  - python=3.13.4
  - pandas=2.2.3
  - sqlalchemy=2.0.39
  - ipykernel=6.29.5
  - pip=25.1
  - pip:
      - duckdb==1.3.0
      - duckdb-engine==0.17.0
