dbt_citibike_trip:
  target: dev
  outputs:
    threads: 1
    location: US
    priority: interactive
    dev:
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('BIGQUERY_CREDENTIALS_PATH') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      threads: 1
      type: bigquery
    config:
      send_anonymous_usage_stats: False