version: 1
default_environment: dev
project_id: 40229ed2-1454-4323-aef7-74030ea7660e
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-duckdb
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-duckdb.git
    config:
      path: ${DUCKDB_PATH}
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      project: ${BIGQUERY_PROJECT}
      dataset: ${BIGQUERY_SOURCE_DATASET}
      method: batch_job
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      credentials_path: ${BIGQUERY_CREDENTIALS_PATH}
      batch_size: 1000000  # Increased batch size
      max_parallelism: 32  # Parallel upload threads
      overwrite: true
      upsert: true
