version: 1
default_environment: dev
project_id: 0da7aa26-0c60-410b-86d7-0748d3deb9d5
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-duckdb
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-duckdb.git
    config:
      flattening_enabled: true
      flattening_max_depth: 1
      path: ${DUCKDB_PATH}
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      project: ${BIGQUERY_PROJECT}
      dataset: ${BIGQUERY_DATASET}
      credentials_path: ${BIGQUERY_CREDENTIALS_PATH}
      method: batch_job
      batch_size: 100000  # Increased batch size
      max_parallelism: 8  # Parallel upload threads
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      write_disposition: MERGE
      merge: true
      upsert: true
      merge_keys:
        - ride_id
      dedupe_before_upsert: true
