Table fact_trips {
  trip_id string [pk] -- same value from source dataset, which should be unique for each trip
  started_at timestamp
  ended_at timestamp
  duration_mins integer
  start_station_key string
  end_station_key string
  distance_metres integer
  membership_type_id string
  bike_type_id string
  price_plan_id integer
  price_paid float
}

Table dim_stations {
  station_key string [pk] -- generated by dbt_utils.generate_surrogate_key
                          -- (['station_id', 'station_name', 'latitude', 'longitude'])
  station_id string
  station_name string
  latitude float
  longitude float
  total_starts integer
  total_ends integer
}

Table dim_membership_types {
  membership_type_id string [pk] -- generated by dbt_utils.generate_surrogate_key
                                 -- (['member_casual'])
  type string
}

Table dim_bike_types {
  bike_type_id string [pk] -- generated by dbt_utils.generate_surrogate_key
                           -- (['rideable_type'])
  type string
}

Table price_plans {
  price_plan_id integer [pk] -- same value from seed CSV, which is an integer from 1 onwards
  membership_type string
  bike_type string
  unlock_fee float
  per_min_pricing float
  included_mins integer
  valid_from date
  valid_to date -- default to max date, 9999-12-31, if plan is valid
}

Ref: fact_trips.bike_type_id > dim_bike_types.bike_type_id
Ref: fact_trips.start_station_key > dim_stations.station_key
Ref: fact_trips.end_station_key > dim_stations.station_key
Ref: fact_trips.membership_type_id > dim_membership_types.membership_type_id
Ref: fact_trips.price_plan_id > price_plans.price_plan_id
