version: 2

models:
  - name: stg_citibike_trip
    description: "Staging table for raw bike trip data with calculated distances"
    columns:
      - name: ride_id
        description: "Unique identifier for each trip"
        tests:
          - unique
          - not_null

      # - name: distance_meters
      #   description: "Calculated trip distance in meters using GIS functions"
      #   tests:
      #     - not_null
      #     - dbt_expectations.expect_column_values_to_be_between:
      #         min_value: 0
      #         strictly: false   # allows 0

      - name: duration_seconds
        description: "Trip duration in seconds"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1      # strictly > 0
              strictly: true

      - name: rideable_type
        description: "Type of bike (classic_bike or electric_bike)"
        tests:
          - accepted_values:
              values: ['electric_bike', 'classic_bike']

      - name: member_casual
        description: "Type of rider (member or casual)"
        tests:
          - accepted_values:
              values: ['member', 'casual']
