version: 2

models:
  - name: stg_world_athletics
    description: "Staging model for World Athletics data with cleaned and standardized fields"
    columns:
      - name: rank
        description: "The ranking of the athlete in this event"
        tests:
          - not_null
      - name: competitor
        description: "Name of the athlete"
        tests:
          - not_null
      - name: date
        description: "Date when the event occurred"
        tests:
          - not_null
      - name: gender
        description: "Gender category of the event (M/F)"
        tests:
          - accepted_values:
              values: ['male', 'female']
      - name: age_cat
        description: "Age category of the event (e.g., U20, SEN)"
        tests:
          - accepted_values:
              values: ['u20', 'senior', 'u18']
      - name: age_at_event
        description: "Age of the athlete at the time of the event (null or >=15)"
        # tests:
        #   - dbt_expectations.expect_column_values_to_be_between:
        #       min_value: 15
        #       max_value: 100
        #       strictly: ">="
        #       row_condition: "age_at_event is not null"
      - name: is_track
        description: "Boolean indicating if this is a track event"
        tests:
          - not_null
      - name: is_field
        description: "Boolean indicating if this is a field event"
        tests:
          - not_null
      - name: is_mixed
        description: "Boolean indicating if this is a mixed event"
        tests:
          - not_null
      - name: mark_unit
        description: "Unit of measurement for the mark (metres, seconds, or points)"
        tests:
          - accepted_values:
              values: ['metres', 'seconds', 'points']